"""Synthetic SD Worx-flavoured corpus. Every failure mode the challenge names is planted on purpose:
outdated version, duplicate copy, conflicting chat message, wrong-country document, missing knowledge."""

PEOPLE = [
    dict(id="els", name="Els Van Damme", role="Senior Payroll Consultant", team="Payroll BE", country="BE", seniority_years=8, email="els.vandamme@sdworx.com", active=True),
    dict(id="marc", name="Marc Dupont", role="Chief Technology Officer", team="Executive", country="BE", seniority_years=22, email="marc.dupont@sdworx.com", active=True),
    dict(id="jan", name="Jan Peeters", role="Time & Absence Specialist", team="Time & Absence BE", country="BE", seniority_years=4, email="jan.peeters@sdworx.com", active=True),
    dict(id="sofie", name="Sofie Janssens", role="HR Advisor", team="HR NL", country="NL", seniority_years=6, email="sofie.janssens@sdworx.com", active=True),
    dict(id="lena", name="Lena Müller", role="Payroll Lead", team="Payroll DE", country="DE", seniority_years=11, email="lena.mueller@sdworx.com", active=True),
    dict(id="tom", name="Tom Verhoeven", role="SAP Integration Architect", team="Integrations", country="BE", seniority_years=9, email="tom.verhoeven@sdworx.com", active=True),
    dict(id="amira", name="Amira Haddad", role="Product Owner eBlox", team="Product", country="BE", seniority_years=5, email="amira.haddad@sdworx.com", active=True),
    dict(id="pieter", name="Pieter De Smet", role="Payroll Consultant (left 2023)", team="Payroll BE", country="BE", seniority_years=3, email=None, active=False),
    dict(id="claire", name="Claire Martin", role="Payroll Consultant", team="Payroll FR", country="FR", seniority_years=7, email="claire.martin@sdworx.com", active=True),
    dict(id="rob", name="Rob Williams", role="Payroll Consultant", team="Payroll UK", country="UK", seniority_years=5, email="rob.williams@sdworx.com", active=True),
    dict(id="nadia", name="Nadia El Amrani", role="Customer Success Manager, Colruyt Group", team="Customer Success BE", country="BE", seniority_years=6, email="nadia.elamrani@sdworx.com", active=True),
    dict(id="koen", name="Koen Wouters", role="Legal Counsel, Employment Law", team="Legal BE", country="BE", seniority_years=12, email="koen.wouters@sdworx.com", active=True),
    dict(id="hanne", name="Hanne Claes", role="HR Business Partner", team="HR BE", country="BE", seniority_years=3, email="hanne.claes@sdworx.com", active=True),
]

# Each document: sections is a list of (heading, [sentences]). Every sentence becomes one line.
DOCS = [
    # ---- Notice periods: outdated v1 (owner left), current v2, and a stray duplicate copy ----
    dict(id="POL-BE-001-v1", title="Belgium – Notice Periods Policy (v1, 2021)", doc_type="policy", source_system="SharePoint",
         country="BE", client=None, team="HR", product=None, topics=["notice_period"],
         owner_id="pieter", author_id="pieter", created_at="2021-06-14", updated_at="2021-06-14", version="1.0",
         supersedes_id=None, location="SharePoint › HR BE › Policies › Archive", url="https://sdworx.sharepoint.com/hr-be/policies/POL-BE-001-v1.docx",
         sections=[
             ("Scope", ["This policy describes the statutory notice periods for white-collar and blue-collar employees under Belgian employment contracts.",
                        "It applies to all Belgian clients serviced by the Payroll BE team."]),
             ("Notice given by the employer", ["For a white-collar employee with 5 years of service the employer notice period is 15 weeks.",
                                              "Between 5 and 10 years of service the notice period increases by 3 weeks per started year of service.",
                                              "Notice periods are expressed in weeks and start on the Monday following notification."]),
             ("Notice given by the employee", ["An employee with 5 years of service must give 7 weeks of notice.",
                                              "Employee notice is capped at 13 weeks regardless of seniority."]),
         ]),
    dict(id="POL-BE-001-v2", title="Belgium – Notice Periods Policy (v2, 2025)", doc_type="policy", source_system="SharePoint",
         country="BE", client=None, team="HR", product=None, topics=["notice_period"],
         owner_id="els", author_id="els", created_at="2025-03-12", updated_at="2025-03-12", version="2.0",
         supersedes_id="POL-BE-001-v1", location="SharePoint › HR BE › Policies", url="https://sdworx.sharepoint.com/hr-be/policies/POL-BE-001-v2.docx",
         sections=[
             ("Scope", ["This policy describes the statutory notice periods for white-collar and blue-collar employees under Belgian employment contracts, following the unified statute.",
                        "It applies to all Belgian clients serviced by the Payroll BE team and replaces version 1 of 2021."]),
             ("Notice given by the employer", ["For a white-collar employee with 5 years of service the employer notice period is 18 weeks.",
                                              "From 5 years of service the notice period increases by 3 weeks per started year of service until 20 years.",
                                              "Notice periods are expressed in weeks and start on the Monday following notification."]),
             ("Notice given by the employee", ["An employee with 5 years of service must give 9 weeks of notice.",
                                              "Employee notice is capped at 13 weeks regardless of seniority."]),
             ("Processing in eBlox", ["Register the notice in eBlox under Contract › Termination with the notification date and the calculated end date.",
                                     "eBlox calculates the severance indemnity automatically when the notice is not performed."]),
         ]),
    dict(id="COPY-BE-001", title="Notice Periods BE (copy)", doc_type="wiki", source_system="SharePoint",
         country="BE", client=None, team="HR", product=None, topics=["notice_period"],
         owner_id=None, author_id="jan", created_at="2025-03-20", updated_at="2025-03-20", version=None,
         supersedes_id=None, location="SharePoint › Personal › Jan Peeters › Notes", url="https://sdworx-my.sharepoint.com/personal/jan_peeters/notes/notice-periods-copy.docx",
         sections=[
             ("Employer notice", ["For a white-collar employee with 5 years of service the employer notice period is 18 weeks.",
                                  "From 5 years of service the notice period increases by 3 weeks per started year of service until 20 years."]),
         ]),

    # ---- Guaranteed salary: owned manual vs. conflicting CTO chat, legal email confirms manual ----
    dict(id="MAN-BE-SICK", title="Belgium – Guaranteed Salary during Sick Leave – Manual", doc_type="manual", source_system="Confluence",
         country="BE", client=None, team="Time & Absence", product="eBlox", topics=["sick_leave_guaranteed_salary"],
         owner_id="jan", author_id="jan", created_at="2023-02-01", updated_at="2024-11-05", version="3.2",
         supersedes_id=None, location="Confluence › Time & Absence BE › Manuals", url="https://sdworx.atlassian.net/wiki/spaces/TABE/pages/MAN-BE-SICK",
         sections=[
             ("Entitlement", ["A white-collar employee in Belgium receives 30 calendar days of guaranteed salary at 100% from the employer during sick leave.",
                              "A blue-collar employee receives 7 days at 100% followed by a reduced percentage up to 30 days.",
                              "After the guaranteed salary period, the health insurance fund (mutualiteit) takes over."]),
             ("Processing in eBlox", ["Enter the sickness period under Absences › Incapacity with the medical certificate dates.",
                                     "eBlox applies the guaranteed salary automatically based on the employee statute and seniority."]),
         ]),
    dict(id="CHAT-TEAMS-8821", title="Teams message in #payroll-be-general", doc_type="chat", source_system="Teams",
         country="BE", client=None, team="Payroll", product=None, topics=["sick_leave_guaranteed_salary"],
         owner_id=None, author_id="marc", created_at="2026-08-14", updated_at="2026-08-14", version=None,
         supersedes_id=None, location="Teams › Payroll BE › #payroll-be-general › 14 Aug 2026 09:12", url="https://teams.microsoft.com/l/message/payroll-be-general/8821",
         sections=[
             ("Message", ["FYI team, with the labour deal reform the guaranteed salary for white-collar employees is now 60 days instead of 30 days.",
                          "Please apply 60 days for all Belgian clients from this month, I will ask someone to update the manual later."]),
         ]),
    dict(id="EMAIL-KOEN-2026-09-02", title="Email: Guaranteed salary reform – status", doc_type="email", source_system="Outlook",
         country="BE", client=None, team="Legal", product=None, topics=["sick_leave_guaranteed_salary"],
         owner_id="koen", author_id="koen", created_at="2026-09-02", updated_at="2026-09-02", version=None,
         supersedes_id=None, location="Outlook › To: payroll-be@sdworx.com › 2 Sep 2026 16:40", url="https://outlook.office.com/mail/id/AAMkAGVm-koen-20260902",
         sections=[
             ("Body", ["The proposal to extend guaranteed salary for white-collar employees to two months has not been enacted and remains a draft bill.",
                       "Until publication in the Belgian Official Gazette, the current rule of 30 calendar days of guaranteed salary continues to apply.",
                       "Please do not change client configurations based on the announcement."]),
         ]),

    # ---- Vacation days: NL policy vs BE policy (wrong country for a Dutch question) ----
    dict(id="POL-NL-VAC", title="Netherlands – Statutory Vacation Days Policy", doc_type="policy", source_system="SharePoint",
         country="NL", client=None, team="HR", product=None, topics=["vacation_days"],
         owner_id="sofie", author_id="sofie", created_at="2025-01-10", updated_at="2025-01-10", version="1.3",
         supersedes_id=None, location="SharePoint › HR NL › Policies", url="https://sdworx.sharepoint.com/hr-nl/policies/POL-NL-VAC.docx",
         sections=[
             ("Statutory entitlement", ["A full-time employee in the Netherlands is entitled to at least 4 times the weekly working hours in vacation per year, which equals 20 days for a 5-day week.",
                                        "Statutory vacation days expire 6 months after the end of the year in which they were accrued, unless the employee was unable to take them."]),
             ("Above-statutory days", ["Collective agreements typically grant 24 to 25 days in total; the extra days expire after 5 years."]),
         ]),
    dict(id="POL-BE-VAC", title="Belgium – Annual Vacation Policy", doc_type="policy", source_system="SharePoint",
         country="BE", client=None, team="Time & Absence", product=None, topics=["vacation_days", "holiday_pay"],
         owner_id="jan", author_id="jan", created_at="2024-04-02", updated_at="2024-04-02", version="2.1",
         supersedes_id=None, location="SharePoint › Time & Absence BE › Policies", url="https://sdworx.sharepoint.com/ta-be/policies/POL-BE-VAC.docx",
         sections=[
             ("Statutory entitlement", ["A full-time employee in Belgium is entitled to 20 days of statutory vacation in a 5-day week, based on the work performed in the previous calendar year.",
                                        "European leave can be taken from the first year of employment as an advance on the following year's double holiday pay."]),
             ("Holiday pay", ["White-collar employees receive single holiday pay as normal salary during vacation and double holiday pay equal to 92% of the gross monthly salary."]),
         ]),

    # ---- Meal vouchers: procedure exists, provider switch for Colruyt has no documented answer (gap) ----
    dict(id="PROC-BE-MEAL", title="Procedure – Changing the Meal Voucher Face Value in eBlox (Belgium)", doc_type="procedure", source_system="Confluence",
         country="BE", client=None, team="Payroll", product="eBlox", topics=["meal_vouchers", "payroll_engine_eblox"],
         owner_id="els", author_id="els", created_at="2025-06-18", updated_at="2025-06-18", version="1.1",
         supersedes_id=None, location="Confluence › Payroll BE › Procedures", url="https://sdworx.atlassian.net/wiki/spaces/PAYBE/pages/PROC-BE-MEAL",
         sections=[
             ("Limits", ["The maximum face value of a meal voucher in Belgium is €8 per worked day, with an employer contribution of at most €6.91 and an employee contribution of at least €1.09.",
                         "Face values above the maximum make the full voucher taxable as salary."]),
             ("Steps in eBlox", ["Open the client in eBlox, go to Client settings › Benefits › Meal vouchers and set the new face value and the effective date.",
                                 "Set the employer and employee split; eBlox validates that the employer part does not exceed €6.91.",
                                 "Run a simulation payroll for one employee and check the voucher line on the payslip before the effective month."]),
         ]),
    dict(id="CHK-COLRUYT", title="Client Checklist – Colruyt Group monthly payroll run", doc_type="checklist", source_system="SharePoint",
         country="BE", client="Colruyt", team="Payroll", product="eBlox", topics=["payroll_engine_eblox", "meal_vouchers"],
         owner_id="nadia", author_id="nadia", created_at="2026-01-08", updated_at="2026-01-08", version="4",
         supersedes_id=None, location="SharePoint › Clients › Colruyt Group › Checklists", url="https://sdworx.sharepoint.com/clients/colruyt/checklists/monthly-run.xlsx",
         sections=[
             ("Before the run", ["Import the time and absence file from Colruyt SAP HCM before the 20th of the month.",
                                 "Check that meal voucher counts match the worked days export from Colruyt's time system."]),
             ("After the run", ["Send the voucher order file to the provider portal on the last working day of the month.",
                                "Archive the payroll journal in the Colruyt client folder."]),
         ]),
    dict(id="JIRA-COL-4412", title="COL-4412 – Colruyt meal voucher provider switch", doc_type="ticket", source_system="Jira",
         country="BE", client="Colruyt", team="Product", product="eBlox", topics=["voucher_provider", "meal_vouchers"],
         owner_id="amira", author_id="nadia", created_at="2026-09-10", updated_at="2026-09-22", version=None,
         supersedes_id=None, location="Jira › COL › COL-4412", url="https://sdworx.atlassian.net/browse/COL-4412",
         sections=[
             ("Description", ["Colruyt is negotiating a switch of meal voucher provider for 2027; contract not signed yet.",
                              "eBlox needs a new provider export format once the provider is confirmed; blocked until Colruyt procurement decides."]),
         ]),

    # ---- Meeting decision ----
    dict(id="MEET-2026-09-15", title="Meeting notes – BE Payroll Guild – Holiday pay for Delhaize", doc_type="meeting", source_system="Meeting Recorder",
         country="BE", client="Delhaize", team="Payroll", product="eBlox", topics=["holiday_pay", "payroll_engine_eblox"],
         owner_id="els", author_id="els", created_at="2026-09-15", updated_at="2026-09-15", version=None,
         supersedes_id=None, location="Teams meeting › BE Payroll Guild › 15 Sep 2026 14:00–14:45 › Room Antwerp 3.12", url="https://sdworx.sharepoint.com/meetings/be-payroll-guild/2026-09-15-notes.docx",
         sections=[
             ("Decisions", ["Decision: from Q4 2026 the double holiday pay for Delhaize white-collar employees is calculated with the eBlox HP2 module instead of the legacy spreadsheet.",
                            "Decision: Els Van Damme owns the migration and Amira Haddad validates the HP2 rounding fix before go-live."]),
             ("Actions", ["Action (Amira): close ticket PAY-2210 on HP2 rounding by 10 October 2026.",
                          "Action (Jan): reconcile 2025 vacation attestations for Delhaize before the first HP2 run."]),
         ]),
    dict(id="JIRA-PAY-2210", title="PAY-2210 – eBlox HP2 double holiday pay rounding differs by €0.01", doc_type="ticket", source_system="Jira",
         country="BE", client="Delhaize", team="Product", product="eBlox", topics=["holiday_pay", "payroll_engine_eblox"],
         owner_id="amira", author_id="els", created_at="2026-09-01", updated_at="2026-09-20", version=None,
         supersedes_id=None, location="Jira › PAY › PAY-2210", url="https://sdworx.atlassian.net/browse/PAY-2210",
         sections=[
             ("Description", ["HP2 rounds double holiday pay per component while the legacy sheet rounds the total, causing €0.01 differences on 3% of Delhaize payslips.",
                              "Fix planned for eBlox release 2026.10."]),
         ]),

    # ---- Other countries and topics for breadth ----
    dict(id="MAN-DE-13", title="Germany – 13th Month and Weihnachtsgeld Handling", doc_type="manual", source_system="Confluence",
         country="DE", client=None, team="Payroll", product="SAP Payroll", topics=["thirteenth_month"],
         owner_id="lena", author_id="lena", created_at="2025-02-20", updated_at="2025-11-03", version="2.0",
         supersedes_id=None, location="Confluence › Payroll DE › Manuals", url="https://sdworx.atlassian.net/wiki/spaces/PAYDE/pages/MAN-DE-13",
         sections=[
             ("Rule", ["In Germany a 13th month or Weihnachtsgeld is not statutory; it follows the collective agreement or employment contract.",
                       "For Siemens the collective agreement grants a Weihnachtsgeld of 55% of the monthly base salary, paid with the November payroll."]),
             ("Processing", ["Enter wage type 2100 in SAP Payroll with the November period; pro-rate for employees who joined during the year."]),
         ]),
    dict(id="MAN-SAP-EBLOX", title="SAP SuccessFactors to eBlox Integration Guide", doc_type="manual", source_system="Confluence",
         country=None, client=None, team="Integrations", product="SAP SuccessFactors", topics=["sap_integration", "payroll_engine_eblox"],
         owner_id="tom", author_id="tom", created_at="2024-09-01", updated_at="2025-08-19", version="5.1",
         supersedes_id=None, location="Confluence › Integrations › SAP", url="https://sdworx.atlassian.net/wiki/spaces/INT/pages/MAN-SAP-EBLOX",
         sections=[
             ("Data flow", ["Employee master data replicates nightly from SAP SuccessFactors Employee Central to eBlox via the point-to-point replication API.",
                            "Absences flow the other way: eBlox posts approved absences back to Employee Central every 4 hours."]),
             ("Mapping", ["Cost centres map one to one; SuccessFactors pay components map to eBlox wage codes through the mapping table INT-MAP-07."]),
         ]),
    dict(id="POL-UK-SSP", title="United Kingdom – Statutory Sick Pay", doc_type="policy", source_system="SharePoint",
         country="UK", client=None, team="Payroll", product=None, topics=["statutory_sick_pay", "sick_leave_guaranteed_salary"],
         owner_id="rob", author_id="rob", created_at="2026-04-06", updated_at="2026-04-06", version="2026/27",
         supersedes_id=None, location="SharePoint › Payroll UK › Policies", url="https://sdworx.sharepoint.com/pay-uk/policies/POL-UK-SSP.docx",
         sections=[
             ("Rate", ["Statutory Sick Pay in the United Kingdom is £118.75 per week for up to 28 weeks, payable from the fourth qualifying day.",
                       "Employees must earn at least the lower earnings limit to qualify."]),
         ]),
    dict(id="WIKI-BE-MOB", title="Belgium – Federal Mobility Budget", doc_type="wiki", source_system="Confluence",
         country="BE", client=None, team="HR", product=None, topics=["mobility_budget"],
         owner_id="koen", author_id="koen", created_at="2025-05-05", updated_at="2025-05-05", version=None,
         supersedes_id=None, location="Confluence › HR BE › Wiki", url="https://sdworx.atlassian.net/wiki/spaces/HRBE/pages/WIKI-BE-MOB",
         sections=[
             ("Pillars", ["The mobility budget replaces a company car with three pillars: an environmentally friendly car, sustainable transport and housing costs, and a cash balance taxed at 38.07%.",
                          "The budget is between €3,000 and €16,875 per year and at most 20% of gross annual salary."]),
         ]),
    dict(id="CHK-BE-ONB", title="Belgium – New Hire Onboarding Checklist", doc_type="checklist", source_system="SharePoint",
         country="BE", client=None, team="HR", product=None, topics=["onboarding"],
         owner_id="hanne", author_id="hanne", created_at="2026-02-11", updated_at="2026-02-11", version="3",
         supersedes_id=None, location="SharePoint › HR BE › Checklists", url="https://sdworx.sharepoint.com/hr-be/checklists/onboarding.xlsx",
         sections=[
             ("Before day one", ["Submit the Dimona declaration to the NSSO before the employee starts, at the latest on the first working day.",
                                 "Collect the signed contract, ID copy and bank details and create the employee in eBlox."]),
         ]),
    dict(id="PROC-BE-TIME", title="Procedure – Time Registration and Overtime Approval (Belgium)", doc_type="procedure", source_system="Confluence",
         country="BE", client=None, team="Time & Absence", product="Protime", topics=["time_registration"],
         owner_id="jan", author_id="jan", created_at="2025-09-30", updated_at="2025-09-30", version="1.0",
         supersedes_id=None, location="Confluence › Time & Absence BE › Procedures", url="https://sdworx.atlassian.net/wiki/spaces/TABE/pages/PROC-BE-TIME",
         sections=[
             ("Overtime", ["Overtime must be approved by the line manager in Protime within 5 working days and is paid with a 50% supplement, or 100% on Sundays and public holidays."]),
         ]),
    dict(id="MAN-FR-13", title="France – Prime de 13e mois", doc_type="manual", source_system="Confluence",
         country="FR", client=None, team="Payroll", product=None, topics=["thirteenth_month"],
         owner_id="claire", author_id="claire", created_at="2025-07-01", updated_at="2025-07-01", version="1.0",
         supersedes_id=None, location="Confluence › Payroll FR › Manuals", url="https://sdworx.atlassian.net/wiki/spaces/PAYFR/pages/MAN-FR-13",
         sections=[
             ("Rule", ["In France the prime de 13e mois is contractual or set by the convention collective; for Carrefour it is paid half in June and half in December."]),
         ]),
]

# Extra graph edges beyond owns/authored (which are derived from the documents).
EDGES = [
    ("marc", "edited", "doc:POL-BE-001-v2", "2025-03-14", "fixed a typo in the scope section"),
    ("els", "answered", "topic:notice_period", "2026-09-03", "Teams question from HR BE about notice for a 7-year employee"),
    ("els", "answered", "topic:notice_period", "2026-06-21", "client escalation Proximus"),
    ("els", "consulted", "topic:notice_period", "2026-04-11", "legal review with Koen Wouters"),
    ("koen", "consulted", "topic:notice_period", "2026-04-11", "legal review with Els Van Damme"),
    ("koen", "reviewed", "doc:POL-BE-001-v2", "2025-03-10", None),
    ("hanne", "answered", "topic:notice_period", "2026-08-02", "HR BE onboarding question"),
    ("jan", "answered", "topic:sick_leave_guaranteed_salary", "2026-07-15", "#payroll-be-general"),
    ("jan", "answered", "topic:vacation_days", "2026-07-30", "#time-absence-be"),
    ("koen", "answered", "topic:sick_leave_guaranteed_salary", "2026-09-02", "email to payroll-be on the reform status"),
    ("sofie", "answered", "topic:vacation_days", "2026-05-19", "#hr-nl"),
    ("amira", "assigned", "doc:JIRA-COL-4412", "2026-09-10", None),
    ("nadia", "consulted", "topic:voucher_provider", "2026-09-18", "Colruyt procurement call"),
    ("amira", "consulted", "topic:voucher_provider", "2026-09-19", "export format scoping"),
    ("els", "attended", "doc:MEET-2026-09-15", "2026-09-15", None),
    ("amira", "attended", "doc:MEET-2026-09-15", "2026-09-15", None),
    ("jan", "attended", "doc:MEET-2026-09-15", "2026-09-15", None),
    ("amira", "assigned", "doc:JIRA-PAY-2210", "2026-09-01", None),
    ("tom", "answered", "topic:sap_integration", "2026-08-28", "#integrations"),
    ("tom", "consulted", "topic:sap_integration", "2026-09-12", "Colruyt SAP HCM file format"),
    ("lena", "answered", "topic:thirteenth_month", "2025-11-20", "#payroll-de"),
    ("marc", "edited", "doc:MAN-BE-SICK", "2023-02-03", "initial formatting"),
]
